export const pathName = {
  USED: '/used',
  NEW: '/new',
  SELL_TRADE: '/sell-trade',
  EV: '/ev',
  MILITARY: '/military',
  BUY_ONLINE: '/buy-online',
  SITE_MAP: '/site-map',
  BLOG: '/blog',
  FAQ: '/faq',
  CONTACT_US: '/contact-us',
  DEALERS: '/dealers',
  PARTNERS: '/partners',
  TRUE_CARD_INC: '/true-card',
  TEAM: '/team',
  CAREERS: '/careers',
  PRESS: '/press',
  DEVELOPERS: '/developers',
  INVESTORS: 'investors'
}